function build_compound_model()
%BUILD_COMPOUND_MODEL  构建复合翼 Simulink 模型 (可直接运行)
%   生成 compound_vtol.slx
%   控制框图: 模式管理 → 升力旋翼+推进器+舵面 → 全包线6DOF → 反馈
%
%   用法:
%     cd E:\drone-simulink; init_project; build_compound_model
%     open_system('compound_vtol')
%     sim('compound_vtol')

    mdl = 'compound_vtol';
    if bdIsLoaded(mdl), close_system(mdl, 0); end
    new_system(mdl); open_system(mdl);

    set_param(mdl, 'Solver','ode4','FixedStep','0.002','StopTime','100');
    set_param(mdl, 'SaveFormat','StructureWithTime');

    %% ========== 任务输入 ==========
    add_block('simulink/Sources/Step', [mdl '/Alt_Cmd'], ...
        'Position',[30,80,70,100], 'Time','0','After','100','Before','0');
    add_block('simulink/Sources/Step', [mdl '/V_Cmd'], ...
        'Position',[30,160,70,180], 'Time','20','After','25','Before','0');

    %% ========== 模式管理器 ==========
    add_block('simulink/Ports & Subsystems/Subsystem', [mdl '/Mode_Mgr'], ...
        'Position',[170,55,350,195], 'BackgroundColor','cyan');
    build_mode_mgr(mdl);

    %% ========== 升力旋翼控制 ==========
    add_block('simulink/Ports & Subsystems/Subsystem', [mdl '/Lift_Ctrl'], ...
        'Position',[420,30,600,110], 'BackgroundColor','green');
    build_lift_ctrl(mdl);

    %% ========== 推进器控制 ==========
    add_block('simulink/Ports & Subsystems/Subsystem', [mdl '/Push_Ctrl'], ...
        'Position',[420,130,600,200], 'BackgroundColor','yellow');
    build_push_ctrl(mdl);

    %% ========== 舵面控制 ==========
    add_block('simulink/Ports & Subsystems/Subsystem', [mdl '/Surf_Ctrl'], ...
        'Position',[420,220,600,310], 'BackgroundColor',[0.8,0.6,1]);
    build_surf_ctrl(mdl);

    %% ========== 复合翼动力学 ==========
    add_block('simulink/Ports & Subsystems/Subsystem', [mdl '/CW_Dyn'], ...
        'Position',[680,30,920,310], 'BackgroundColor','red');
    build_cw_dyn(mdl);

    %% ========== Demux ==========
    add_block('simulink/Signal Routing/Demux', [mdl '/Demux'], ...
        'Position',[970,50,975,280], 'Outputs','12');

    %% ========== 反馈 Mux ==========
    add_mux(mdl, 'Mux_Fb', 6, [110,340,115,450]);

    %% ========== Scope ==========
    add_block('simulink/Sinks/Scope', [mdl '/Scope_Alt'], ...
        'Position',[1050,40,1090,80], 'NumInputPorts','2');
    add_block('simulink/Sinks/Scope', [mdl '/Scope_Motor'], ...
        'Position',[1050,110,1090,150]);
    add_block('simulink/Sinks/To Workspace', [mdl '/ToWS'], ...
        'VariableName','cw_state','Position',[1050,180,1090,210]);

    %% ========== 顶层连线 ==========
    add_line(mdl, 'Alt_Cmd/1', 'Mode_Mgr/1');
    add_line(mdl, 'V_Cmd/1',   'Mode_Mgr/2');

    add_line(mdl, 'Mode_Mgr/1', 'Lift_Ctrl/1');
    add_line(mdl, 'Mode_Mgr/2', 'Push_Ctrl/1');
    add_line(mdl, 'Mode_Mgr/1', 'Surf_Ctrl/1');
    add_line(mdl, 'Alt_Cmd/1',  'Lift_Ctrl/2');

    add_line(mdl, 'Lift_Ctrl/1',  'CW_Dyn/1');
    add_line(mdl, 'Push_Ctrl/1',  'CW_Dyn/2');
    add_line(mdl, 'Surf_Ctrl/1',  'CW_Dyn/3');
    add_line(mdl, 'Surf_Ctrl/2',  'CW_Dyn/4');
    add_line(mdl, 'Surf_Ctrl/3',  'CW_Dyn/5');

    add_line(mdl, 'CW_Dyn/1', 'Demux/1');

    % 反馈
    add_line(mdl, 'Demux/1', 'Mux_Fb/1');
    add_line(mdl, 'Demux/2', 'Mux_Fb/2');
    add_line(mdl, 'Demux/3', 'Mux_Fb/3');
    add_line(mdl, 'Demux/7', 'Mux_Fb/4');
    add_line(mdl, 'Demux/8', 'Mux_Fb/5');
    add_line(mdl, 'Demux/9', 'Mux_Fb/6');
    add_line(mdl, 'Mux_Fb/1', 'Mode_Mgr/3');

    add_line(mdl, 'Alt_Cmd/1', 'Scope_Alt/1');
    add_line(mdl, 'Demux/3',   'Scope_Alt/2');
    add_line(mdl, 'Demux/1',   'ToWS/1');

    %% 保存
    save_system(mdl, fullfile(pwd, [mdl '.slx']));
    fprintf('已生成: %s.slx — 打开后可直接运行\n', mdl);
end

%% ==================== 模式管理器 ====================
function build_mode_mgr(mdl)
    sys = [mdl '/Mode_Mgr'];
    delete_line(sys, 'In1/1', 'Out1/1');
    delete_block([sys '/In1']); delete_block([sys '/Out1']);

    add_block('simulink/Sources/In1', [sys '/alt_cmd'], 'Position',[20,40,40,55]);
    add_block('simulink/Sources/In1', [sys '/V_cmd'],   'Position',[20,100,40,115]);
    add_block('simulink/Sources/In1', [sys '/fb'],      'Position',[20,160,40,175]);
    add_block('simulink/Sinks/Out1',  [sys '/mode'],    'Position',[320,35,340,50]);
    add_block('simulink/Sinks/Out1',  [sys '/V_des'],   'Position',[320,100,340,115]);

    % Demux 反馈: [x,y,z,phi,theta,psi]
    add_block('simulink/Signal Routing/Demux', [sys '/Dfb'], ...
        'Position',[70,145,75,215], 'Outputs','6');

    % mode: 0=hover, 1=transition, 2=cruise (基于空速)
    add_block('simulink/Math Operations/Sum of Elements', [sys '/Vsum'], ...
        'Position',[120,40,140,60]);
    add_block('simulink/Math Operations/Math Function', [sys '/Vsqrt'], ...
        'Position',[170,40,200,60], 'Operator','sqrt');
    add_block('simulink/Discontinuities/Saturation', [sys '/Sat'], ...
        'Position',[240,40,280,60], 'UpperLimit','2','LowerLimit','0');

    add_line(sys, 'V_cmd/1','Vsum/1');
    add_line(sys, 'Vsum/1','Vsqrt/1');
    add_line(sys, 'Vsqrt/1','Sat/1');
    add_line(sys, 'Sat/1','mode/1');
    add_line(sys, 'V_cmd/1','V_des/1');
end

%% ==================== 升力旋翼控制 ====================
function build_lift_ctrl(mdl)
    sys = [mdl '/Lift_Ctrl'];
    delete_line(sys, 'In1/1', 'Out1/1');
    delete_block([sys '/In1']); delete_block([sys '/Out1']);

    add_block('simulink/Sources/In1', [sys '/mode'],    'Position',[20,40,40,55]);
    add_block('simulink/Sources/In1', [sys '/alt_des'], 'Position',[20,100,40,115]);
    add_block('simulink/Sinks/Out1',  [sys '/lift_cmd'],'Position',[400,55,420,70]);

    % hover omega = sqrt(m*g/(4*kt)) = sqrt(15*9.81/(4*1.3e-5)) ~ 532
    add_block('simulink/Sources/Constant', [sys '/w0'], ...
        'Position',[80,55,130,75], 'Value','532');
    add_block('simulink/Math Operations/Sum', [sys '/Se'], ...
        'Position',[180,40,200,60], 'Inputs','+-');
    add_block('simulink/Continuous/PID Controller', [sys '/PID_Z'], ...
        'Position',[240,35,340,65], 'P','2.0','I','0.3','D','1.0', ...
        'UpperSaturationLimit','300','LowerSaturationLimit','-300');
    add_block('simulink/Math Operations/Sum', [sys '/Sw'], ...
        'Position',[360,50,380,70], 'Inputs','++');

    add_line(sys, 'alt_des/1','Se/1');
    add_line(sys, 'Se/1','PID_Z/1');
    add_line(sys, 'w0/1','Sw/1');
    add_line(sys, 'PID_Z/1','Sw/2');
    add_line(sys, 'Sw/1','lift_cmd/1');
end

%% ==================== 推进器控制 ====================
function build_push_ctrl(mdl)
    sys = [mdl '/Push_Ctrl'];
    delete_line(sys, 'In1/1', 'Out1/1');
    delete_block([sys '/In1']); delete_block([sys '/Out1']);

    add_block('simulink/Sources/In1', [sys '/V_des'],    'Position',[20,50,40,65]);
    add_block('simulink/Sinks/Out1',  [sys '/push_cmd'], 'Position',[280,50,300,65]);

    add_block('simulink/Math Operations/Gain', [sys '/G'], ...
        'Position',[100,45,160,65], 'Gain','60');
    add_block('simulink/Discontinuities/Saturation', [sys '/Sat'], ...
        'Position',[200,45,240,65], 'UpperLimit','2000','LowerLimit','0');

    add_line(sys, 'V_des/1','G/1');
    add_line(sys, 'G/1','Sat/1');
    add_line(sys, 'Sat/1','push_cmd/1');
end

%% ==================== 舵面控制 ====================
function build_surf_ctrl(mdl)
    sys = [mdl '/Surf_Ctrl'];
    delete_line(sys, 'In1/1', 'Out1/1');
    delete_block([sys '/In1']); delete_block([sys '/Out1']);

    add_block('simulink/Sources/In1', [sys '/mode'], 'Position',[20,50,40,65]);
    add_block('simulink/Sinks/Out1',  [sys '/elev'], 'Position',[280,25,300,40]);
    add_block('simulink/Sinks/Out1',  [sys '/ail'],  'Position',[280,70,300,85]);
    add_block('simulink/Sinks/Out1',  [sys '/rud'],  'Position',[280,115,300,130]);

    % 简化: 舵面在巡航模式下生效
    add_block('simulink/Sources/Constant', [sys '/c0'], 'Position',[100,25,140,40], 'Value','0');
    add_block('simulink/Sources/Constant', [sys '/c1'], 'Position',[100,70,140,85], 'Value','0');
    add_block('simulink/Sources/Constant', [sys '/c2'], 'Position',[100,115,140,130],'Value','0');

    add_line(sys, 'c0/1','elev/1');
    add_line(sys, 'c1/1','ail/1');
    add_line(sys, 'c2/1','rud/1');
end

%% ==================== 复合翼动力学子系统 ====================
function build_cw_dyn(mdl)
    sys = [mdl '/CW_Dyn'];
    delete_line(sys, 'In1/1', 'Out1/1');
    delete_block([sys '/In1']); delete_block([sys '/Out1']);

    add_block('simulink/Sources/In1', [sys '/lift'], 'Position',[20,30,40,45]);
    add_block('simulink/Sources/In1', [sys '/push'], 'Position',[20,80,40,95]);
    add_block('simulink/Sources/In1', [sys '/elev'], 'Position',[20,130,40,145]);
    add_block('simulink/Sources/In1', [sys '/ail'],  'Position',[20,180,40,195]);
    add_block('simulink/Sources/In1', [sys '/rud'],  'Position',[20,230,40,245]);
    add_block('simulink/Sinks/Out1',  [sys '/state'],'Position',[540,120,560,135]);

    add_block('simulink/User-Defined Functions/MATLAB Function', [sys '/cw6dof'], ...
        'Position',[120,40,390,250]);

    set_mafcn_code(sys, 'cw6dof');

    add_block('simulink/Continuous/Integrator', [sys '/Int'], ...
        'Position',[430,80,480,190], ...
        'InitialCondition','[0;0;-50;0;0;0;0;0;0;0;0;0]');

    add_line(sys, 'lift/1','cw6dof/1');
    add_line(sys, 'push/1','cw6dof/2');
    add_line(sys, 'elev/1','cw6dof/3');
    add_line(sys, 'ail/1','cw6dof/4');
    add_line(sys, 'rud/1','cw6dof/5');
    add_line(sys, 'Int/1','cw6dof/6');
    add_line(sys, 'cw6dof/1','Int/1');
    add_line(sys, 'Int/1','state/1');
end

%% ==================== 设置 MATLAB Function 代码 ====================
function set_mafcn_code(sys, blk_name)
    blk_path = [sys '/' blk_name];
    rt = sfroot;
    all_blocks = rt.find('-isa','Stateflow.EMChart');
    target = [];
    for i = 1:numel(all_blocks)
        if contains(all_blocks(i).Path, blk_path)
            target = all_blocks(i);
            break;
        end
    end
    if isempty(target)
        try
            target = get_param(blk_path, 'SFChartObject');
        catch
            warning('无法设置 MATLAB Function 代码, 请手动编辑 %s', blk_path);
            return;
        end
    end

    code = [
        'function state_dot = cw6dof(lift, push, elev, ail, rud, state)' newline ...
        '%#codegen' newline ...
        '%% 复合翼 6DOF 动力学 (升力旋翼+推进器+气动面)' newline ...
        'm = 15; g = 9.81; rho = 1.225;' newline ...
        'S = 1.0; b = 3.5; c = S/b; AR = b^2/S;' newline ...
        'Ixx = 1.0; Iyy = 2.0; Izz = 2.5;' newline ...
        '' newline ...
        '% 升力旋翼参数' newline ...
        'kt = 1.3e-5; kd = 1.8e-7; arm = 1.0;' newline ...
        '' newline ...
        '% 气动系数' newline ...
        'CL0 = 0.2; CLa = 5.5; CD0 = 0.02; e_os = 0.8;' newline ...
        'a_stall = 15*pi/180;' newline ...
        'Cm0 = 0.05; Cma = -1.0; Cmq = -15; Cmde = -0.5;' newline ...
        'Clb = -0.05; Clp = -0.5; Clda = 0.2;' newline ...
        'Cnb = 0.06; Cnr = -0.1; Cndr = 0.05;' newline ...
        '' newline ...
        '% 状态解包' newline ...
        'x=state(1); y=state(2); z=state(3);' newline ...
        'vx=state(4); vy=state(5); vz=state(6);' newline ...
        'phi=state(7); theta=state(8); psi=state(9);' newline ...
        'p=state(10); q=state(11); r=state(12);' newline ...
        '' newline ...
        '% 升力旋翼推力 (4个固定朝上)' newline ...
        'T_lift = 4*kt*lift^2;' newline ...
        '' newline ...
        '% 推进器推力 (机头方向)' newline ...
        'T_push = 3.0e-5*push^2;' newline ...
        '' newline ...
        '% 空速和气动' newline ...
        'V = sqrt(vx^2+vy^2+vz^2) + 1e-6;' newline ...
        'alpha = atan2(vz, vx);' newline ...
        'beta = asin(vy/V);' newline ...
        'qbar = 0.5*rho*V^2;' newline ...
        '' newline ...
        '% 升力系数 (C1 连续失速)' newline ...
        'if alpha < a_stall' newline ...
        '    CL = CL0 + CLa*alpha;' newline ...
        'else' newline ...
        '    CL = CL0 + CLa*a_stall - 2*CLa*(alpha-a_stall);' newline ...
        'end' newline ...
        'CL = max(min(CL, 1.5), -1.0);' newline ...
        'CD = CD0 + CL^2/(pi*e_os*AR);' newline ...
        '' newline ...
        '% 气动力' newline ...
        'L = qbar*S*CL;' newline ...
        'D = qbar*S*CD;' newline ...
        'Y = qbar*S*(-0.3)*beta;' newline ...
        '' newline ...
        '% 舵面力矩' newline ...
        'M_elev = qbar*S*c*Cmde*elev;' newline ...
        'L_ail  = qbar*S*b*Clda*ail;' newline ...
        'N_rud  = qbar*S*b*Cndr*rud;' newline ...
        '' newline ...
        '% 气动力矩' newline ...
        'Vc = V*c/2; Vb = V*b/2;' newline ...
        'M_pitch = qbar*S*c*(Cm0+Cma*alpha+Cmq*q*Vc/V) + M_elev;' newline ...
        'M_roll  = qbar*S*b*(Clb*beta+Clp*p*Vb/V) + L_ail;' newline ...
        'M_yaw   = qbar*S*b*(Cnb*beta+Cnr*r*Vb/V) + N_rud;' newline ...
        '' newline ...
        '% 旋翼力矩' newline ...
        'tau_roll  = arm*kt*lift^2 * 0.5;' newline ...
        'tau_pitch = arm*kt*lift^2 * 0.3;' newline ...
        'tau_yaw   = kd*lift^2 * 2;' newline ...
        '' newline ...
        '% 旋转矩阵' newline ...
        'cp=cos(phi); sp=sin(phi);' newline ...
        'ct=cos(theta); st=sin(theta);' newline ...
        'cb=cos(psi); sb=sin(psi);' newline ...
        '' newline ...
        '% 机体合力' newline ...
        'ca=cos(alpha); sa=sin(alpha);' newline ...
        'Fx = T_push - D*ca + L*sa;' newline ...
        'Fy = Y;' newline ...
        'Fz = T_lift - D*sa - L*ca;' newline ...
        '' newline ...
        '% 加速度' newline ...
        'ax = Fx/m - g*st;' newline ...
        'ay = Fy/m + g*ct*sp;' newline ...
        'az = Fz/m + g*ct*cp;' newline ...
        '' newline ...
        '% 角加速度 (气动+旋翼力矩)' newline ...
        'p_dot = (M_roll+tau_roll + (Iyy-Izz)*q*r) / Ixx;' newline ...
        'q_dot = (M_pitch+tau_pitch + (Izz-Ixx)*p*r) / Iyy;' newline ...
        'r_dot = (M_yaw+tau_yaw + (Ixx-Iyy)*p*q) / Izz;' newline ...
        '' newline ...
        '% 欧拉角导数' newline ...
        'phi_dot   = p + q*sp*(st/ct) + r*cp*(st/ct);' newline ...
        'theta_dot = q*cp - r*sp;' newline ...
        'psi_dot   = q*sp/ct + r*cp/ct;' newline ...
        '' newline ...
        '% 世界坐标速度' newline ...
        'vx_w = ct*cb*vx + (sp*st*cb-cp*sb)*vy + (cp*st*cb+sp*sb)*vz;' newline ...
        'vy_w = ct*sb*vx + (sp*st*sb+cp*cb)*vy + (cp*st*sb-sp*cb)*vz;' newline ...
        'vz_w = -st*vx + sp*ct*vy + cp*ct*vz;' newline ...
        '' newline ...
        'state_dot = [vx_w;vy_w;vz_w; ax;ay;az;' newline ...
        '             phi_dot;theta_dot;psi_dot;' newline ...
        '             p_dot;q_dot;r_dot];' newline ...
        'end' newline
    ];

    try
        target.Script = code;
    catch
        try
            eml = target.find('-isa','Stateflow.EMFunction');
            if ~isempty(eml), eml(1).Script = code; end
        catch
            warning('自动设置代码失败, 请手动编辑 %s 中的 MATLAB Function', blk_path);
        end
    end
end

%% ==================== 工具函数 ====================
function add_mux(mdl, name, n, pos)
    add_block('simulink/Signal Routing/Mux', [mdl '/' name], ...
        'Position', pos, 'Inputs', num2str(n));
end
