function build_fixedwing_model()
%BUILD_FIXEDWING_MODEL  构建固定翼 Simulink 模型 (可直接运行)
%   生成 fixedwing_control.slx
%   控制框图: 高度/空速 → 升降舵+油门  |  航向 → 副翼+方向舵  |  6DOF气动
%
%   用法:
%     cd E:\drone-simulink; init_project; build_fixedwing_model
%     open_system('fixedwing_control')
%     sim('fixedwing_control')

    mdl = 'fixedwing_control';
    if bdIsLoaded(mdl), close_system(mdl, 0); end
    new_system(mdl); open_system(mdl);

    set_param(mdl, 'Solver','ode4','FixedStep','0.002','StopTime','60');
    set_param(mdl, 'SaveFormat','StructureWithTime');

    %% ========== 期望输入 ==========
    add_block('simulink/Sources/Constant', [mdl '/Alt_Des'], ...
        'Position',[30,80,70,100], 'Value','100');
    add_block('simulink/Sources/Constant', [mdl '/Hdg_Des'], ...
        'Position',[30,160,70,180], 'Value','0');
    add_block('simulink/Sources/Constant', [mdl '/V_Des'], ...
        'Position',[30,240,70,260], 'Value','25');

    %% ========== 高度控制子系统 ==========
    add_block('simulink/Ports & Subsystems/Subsystem', [mdl '/Alt_Ctrl'], ...
        'Position',[180,60,380,130], 'BackgroundColor','cyan');
    build_alt_ctrl(mdl);

    %% ========== 航向控制子系统 ==========
    add_block('simulink/Ports & Subsystems/Subsystem', [mdl '/Hdg_Ctrl'], ...
        'Position',[180,150,380,220], 'BackgroundColor','green');
    build_hdg_ctrl(mdl);

    %% ========== 气动动力学子系统 ==========
    add_block('simulink/Ports & Subsystems/Subsystem', [mdl '/FW_Dyn'], ...
        'Position',[500,60,740,270], 'BackgroundColor','red');
    build_fw_dyn(mdl);

    %% ========== Demux 状态 ==========
    add_block('simulink/Signal Routing/Demux', [mdl '/Demux'], ...
        'Position',[790,80,795,260], 'Outputs','12');

    %% ========== 反馈 Mux ==========
    add_mux(mdl, 'Mux_FbAlt', 5, [130,300,135,400]);
    add_mux(mdl, 'Mux_FbHdg', 5, [130,420,135,510]);

    %% ========== Scope ==========
    add_block('simulink/Sinks/Scope', [mdl '/Scope_Alt'], ...
        'Position',[900,50,940,90], 'NumInputPorts','2');
    add_block('simulink/Sinks/Scope', [mdl '/Scope_Hdg'], ...
        'Position',[900,120,940,160], 'NumInputPorts','2');
    add_block('simulink/Sinks/Scope', [mdl '/Scope_Surf'], ...
        'Position',[900,190,940,220]);
    add_block('simulink/Sinks/To Workspace', [mdl '/ToWS'], ...
        'VariableName','fw_state','Position',[900,250,940,280]);

    %% ========== 顶层连线 ==========
    % 期望 → 控制器
    add_line(mdl, 'Alt_Des/1', 'Alt_Ctrl/1');
    add_line(mdl, 'V_Des/1',   'Alt_Ctrl/2');
    add_line(mdl, 'Hdg_Des/1', 'Hdg_Ctrl/1');

    % 控制器 → 动力学
    add_line(mdl, 'Alt_Ctrl/1', 'FW_Dyn/1');   % elevator
    add_line(mdl, 'Alt_Ctrl/2', 'FW_Dyn/2');   % throttle
    add_line(mdl, 'Hdg_Ctrl/1', 'FW_Dyn/3');   % aileron
    add_line(mdl, 'Hdg_Ctrl/2', 'FW_Dyn/4');   % rudder

    % 动力学 → Demux
    add_line(mdl, 'FW_Dyn/1', 'Demux/1');

    % 高度反馈: z, theta, vx, vy, vz
    add_line(mdl, 'Demux/3', 'Mux_FbAlt/1');
    add_line(mdl, 'Demux/8', 'Mux_FbAlt/2');
    add_line(mdl, 'Demux/4', 'Mux_FbAlt/3');
    add_line(mdl, 'Demux/5', 'Mux_FbAlt/4');
    add_line(mdl, 'Demux/6', 'Mux_FbAlt/5');
    add_line(mdl, 'Mux_FbAlt/1', 'Alt_Ctrl/3');

    % 航向反馈: psi, phi, p, q, r
    add_line(mdl, 'Demux/9',  'Mux_FbHdg/1');
    add_line(mdl, 'Demux/7',  'Mux_FbHdg/2');
    add_line(mdl, 'Demux/10', 'Mux_FbHdg/3');
    add_line(mdl, 'Demux/11', 'Mux_FbHdg/4');
    add_line(mdl, 'Demux/12', 'Mux_FbHdg/5');
    add_line(mdl, 'Mux_FbHdg/1', 'Hdg_Ctrl/3');

    % Scope
    add_line(mdl, 'Alt_Des/1', 'Scope_Alt/1');
    add_line(mdl, 'Demux/3',   'Scope_Alt/2');
    add_line(mdl, 'Hdg_Des/1', 'Scope_Hdg/1');
    add_line(mdl, 'Demux/9',   'Scope_Hdg/2');
    add_line(mdl, 'Demux/1',   'ToWS/1');

    %% 保存
    save_system(mdl, fullfile(pwd, [mdl '.slx']));
    fprintf('已生成: %s.slx — 打开后可直接运行\n', mdl);
end

%% ==================== 高度控制子系统 ====================
function build_alt_ctrl(mdl)
    sys = [mdl '/Alt_Ctrl'];
    delete_line(sys, 'In1/1', 'Out1/1');
    delete_block([sys '/In1']); delete_block([sys '/Out1']);

    add_block('simulink/Sources/In1', [sys '/alt_des'],  'Position',[20,40,40,55]);
    add_block('simulink/Sources/In1', [sys '/V_des'],    'Position',[20,100,40,115]);
    add_block('simulink/Sources/In1', [sys '/fb'],       'Position',[20,180,40,195]);
    add_block('simulink/Sinks/Out1',  [sys '/elevator'], 'Position',[700,40,720,55]);
    add_block('simulink/Sinks/Out1',  [sys '/throttle'], 'Position',[700,120,720,135]);

    % Demux 反馈: [z, theta, vx, vy, vz]
    add_block('simulink/Signal Routing/Demux', [sys '/Dfb'], ...
        'Position',[70,165,75,230], 'Outputs','5');

    % 高度误差 (z负值=向上, 所以取反)
    add_block('simulink/Math Operations/Gain', [sys '/NegZ'], ...
        'Position',[110,175,140,195], 'Gain','-1');
    add_block('simulink/Math Operations/Sum', [sys '/Se'], ...
        'Position',[180,40,200,60], 'Inputs','+-');

    % 高度PID → 俯仰角期望
    add_block('simulink/Continuous/PID Controller', [sys '/PID_Alt'], ...
        'Position',[240,35,340,65], 'P','0.5','I','0.02','D','0.3', ...
        'UpperSaturationLimit','0.52','LowerSaturationLimit','-0.52');

    % 俯仰角误差
    add_block('simulink/Math Operations/Sum', [sys '/Se2'], ...
        'Position',[390,40,410,60], 'Inputs','+-');

    % 俯仰PID → 升降舵
    add_block('simulink/Continuous/PID Controller', [sys '/PID_Pitch'], ...
        'Position',[450,35,560,65], 'P','2.0','I','0.1','D','0.5', ...
        'UpperSaturationLimit','0.52','LowerSaturationLimit','-0.52');

    % 空速计算: V = sqrt(vx^2+vy^2+vz^2)
    add_block('simulink/Math Operations/Math Function', [sys '/Vx2'], ...
        'Position',[110,95,140,115], 'Operator','square');
    add_block('simulink/Math Operations/Math Function', [sys '/Vy2'], ...
        'Position',[110,125,140,145], 'Operator','square');
    add_block('simulink/Math Operations/Math Function', [sys '/Vz2'], ...
        'Position',[110,155,140,175], 'Operator','square');
    add_block('simulink/Math Operations/Sum', [sys '/Vsum'], ...
        'Position',[170,110,190,140], 'Inputs','+++');
    add_block('simulink/Math Operations/Math Function', [sys '/Vsqrt'], ...
        'Position',[220,110,250,140], 'Operator','sqrt');

    % 空速误差
    add_block('simulink/Math Operations/Sum', [sys '/SV'], ...
        'Position',[290,110,310,130], 'Inputs','+-');

    % 空速PID → 油门
    add_block('simulink/Continuous/PID Controller', [sys '/PID_V'], ...
        'Position',[350,105,460,135], 'P','0.3','I','0.05','D','0.01', ...
        'UpperSaturationLimit','1','LowerSaturationLimit','0');

    % 连线
    add_line(sys, 'alt_des/1','Se/1');
    add_line(sys, 'fb/1','Dfb/1');
    add_line(sys, 'Dfb/1','NegZ/1');
    add_line(sys, 'NegZ/1','Se/2');
    add_line(sys, 'Se/1','PID_Alt/1');
    add_line(sys, 'PID_Alt/1','Se2/1');
    add_line(sys, 'Dfb/2','Se2/2');
    add_line(sys, 'Se2/1','PID_Pitch/1');
    add_line(sys, 'PID_Pitch/1','elevator/1');

    add_line(sys, 'Dfb/3','Vx2/1'); add_line(sys, 'Dfb/4','Vy2/1'); add_line(sys, 'Dfb/5','Vz2/1');
    add_line(sys, 'Vx2/1','Vsum/1'); add_line(sys, 'Vy2/1','Vsum/2'); add_line(sys, 'Vz2/1','Vsum/3');
    add_line(sys, 'Vsum/1','Vsqrt/1');
    add_line(sys, 'V_des/1','SV/1'); add_line(sys, 'Vsqrt/1','SV/2');
    add_line(sys, 'SV/1','PID_V/1');
    add_line(sys, 'PID_V/1','throttle/1');
end

%% ==================== 航向控制子系统 ====================
function build_hdg_ctrl(mdl)
    sys = [mdl '/Hdg_Ctrl'];
    delete_line(sys, 'In1/1', 'Out1/1');
    delete_block([sys '/In1']); delete_block([sys '/Out1']);

    add_block('simulink/Sources/In1', [sys '/hdg_des'], 'Position',[20,50,40,65]);
    add_block('simulink/Sources/In1', [sys '/fb'],      'Position',[20,160,40,175]);
    add_block('simulink/Sinks/Out1',  [sys '/aileron'], 'Position',[660,40,680,55]);
    add_block('simulink/Sinks/Out1',  [sys '/rudder'],  'Position',[660,130,680,145]);

    % Demux 反馈: [psi, phi, p, q, r]
    add_block('simulink/Signal Routing/Demux', [sys '/Dfb'], ...
        'Position',[70,145,75,210], 'Outputs','5');

    % 航向误差
    add_block('simulink/Math Operations/Sum', [sys '/Se'], ...
        'Position',[130,50,150,70], 'Inputs','+-');

    % 航向PID → 滚转角期望
    add_block('simulink/Continuous/PID Controller', [sys '/PID_Hdg'], ...
        'Position',[190,45,290,75], 'P','1.0','I','0.05','D','0.2', ...
        'UpperSaturationLimit','0.78','LowerSaturationLimit','-0.78');

    % 滚转误差
    add_block('simulink/Math Operations/Sum', [sys '/Se2'], ...
        'Position',[340,45,360,65], 'Inputs','+-');

    % 滚转PID → 副翼
    add_block('simulink/Continuous/PID Controller', [sys '/PID_Roll'], ...
        'Position',[400,40,510,70], 'P','3.0','I','0.1','D','0.5', ...
        'UpperSaturationLimit','0.44','LowerSaturationLimit','-0.44');

    % 侧滑→方向舵 (协调转弯)
    add_block('simulink/Math Operations/Gain', [sys '/Kbeta'], ...
        'Position',[200,155,260,175], 'Gain','-0.5');

    % 连线
    add_line(sys, 'hdg_des/1','Se/1'); add_line(sys, 'Dfb/1','Se/2');
    add_line(sys, 'Se/1','PID_Hdg/1');
    add_line(sys, 'PID_Hdg/1','Se2/1'); add_line(sys, 'Dfb/2','Se2/2');
    add_line(sys, 'Se2/1','PID_Roll/1');
    add_line(sys, 'PID_Roll/1','aileron/1');
    add_line(sys, 'Dfb/3','Kbeta/1');
    add_line(sys, 'Kbeta/1','rudder/1');
end

%% ==================== 固定翼气动动力学子系统 ====================
function build_fw_dyn(mdl)
    sys = [mdl '/FW_Dyn'];
    delete_line(sys, 'In1/1', 'Out1/1');
    delete_block([sys '/In1']); delete_block([sys '/Out1']);

    add_block('simulink/Sources/In1', [sys '/elev'], 'Position',[20,40,40,55]);
    add_block('simulink/Sources/In1', [sys '/thr'],  'Position',[20,100,40,115]);
    add_block('simulink/Sources/In1', [sys '/ail'],  'Position',[20,160,40,175]);
    add_block('simulink/Sources/In1', [sys '/rud'],  'Position',[20,220,40,235]);
    add_block('simulink/Sinks/Out1',  [sys '/state'],'Position',[520,110,540,125]);

    % MATLAB Function block — 6DOF + 气动
    add_block('simulink/User-Defined Functions/MATLAB Function', [sys '/fw6dof'], ...
        'Position',[130,50,370,230]);

    set_mafcn_code(sys, 'fw6dof');

    % 积分器
    add_block('simulink/Continuous/Integrator', [sys '/Int'], ...
        'Position',[410,80,460,170], ...
        'InitialCondition','[0;0;-100;25;0;0;0;0.05;0;0;0;0]');

    add_line(sys, 'elev/1','fw6dof/1');
    add_line(sys, 'thr/1','fw6dof/2');
    add_line(sys, 'ail/1','fw6dof/3');
    add_line(sys, 'rud/1','fw6dof/4');
    add_line(sys, 'Int/1','fw6dof/5');
    add_line(sys, 'fw6dof/1','Int/1');
    add_line(sys, 'Int/1','state/1');
end

%% ==================== 设置 MATLAB Function 代码 ====================
function set_mafcn_code(sys, blk_name)
    blk_path = [sys '/' blk_name];
    rt = sfroot;
    all_blocks = rt.find('-isa','Stateflow.EMChart');
    target = [];
    for i = 1:numel(all_blocks)
        if contains(all_blocks(i).Path, blk_path)
            target = all_blocks(i);
            break;
        end
    end
    if isempty(target)
        try
            target = get_param(blk_path, 'SFChartObject');
        catch
            warning('无法设置 MATLAB Function 代码, 请手动编辑 %s', blk_path);
            return;
        end
    end

    code = [
        'function state_dot = fw6dof(elev, thr, ail, rud, state)' newline ...
        '%#codegen' newline ...
        '%% 固定翼 6DOF + 气动动力学' newline ...
        'm = 10; g = 9.81; rho = 1.225;' newline ...
        'S = 0.5; b = 2.0; c = 0.25;  % 翼面积/翼展/弦长' newline ...
        'Ixx = 0.5; Iyy = 1.0; Izz = 1.2; Ixz = 0.02;' newline ...
        '' newline ...
        '% 气动系数' newline ...
        'CL0 = 0.2; CLa = 5.0; a_stall = 15*pi/180;' newline ...
        'CD0 = 0.02; e_os = 0.8; AR = b^2/S;' newline ...
        'CYb = -0.3;' newline ...
        'Cm0 = 0.05; Cma = -1.0; Cmq = -15; Cmde = -0.5;' newline ...
        'Clb = -0.05; Clp = -0.5; Clda = 0.2;' newline ...
        'Cnb = 0.06; Cnr = -0.1; Cndr = 0.05;' newline ...
        '' newline ...
        '% 状态解包' newline ...
        'x=state(1); y=state(2); z=state(3);' newline ...
        'vx=state(4); vy=state(5); vz=state(6);' newline ...
        'phi=state(7); theta=state(8); psi=state(9);' newline ...
        'p=state(10); q=state(11); r=state(12);' newline ...
        '' newline ...
        '% 空速和迎角/侧滑角' newline ...
        'V = sqrt(vx^2+vy^2+vz^2) + 1e-6;' newline ...
        'alpha = atan2(vz, vx);' newline ...
        'beta = asin(vy/V);' newline ...
        '' newline ...
        '% C1 连续失速升力系数' newline ...
        'if alpha < a_stall' newline ...
        '    CL = CL0 + CLa*alpha;' newline ...
        'else' newline ...
        '    CL = CL0 + CLa*a_stall - 2*CLa*(alpha-a_stall);' newline ...
        'end' newline ...
        'CL = max(min(CL, 1.5), -1.0);' newline ...
        '' newline ...
        '% 阻力系数' newline ...
        'CD = CD0 + CL^2/(pi*e_os*AR);' newline ...
        '' newline ...
        '% 气动力 (风轴)' newline ...
        'qbar = 0.5*rho*V^2;  % 动压' newline ...
        'L = qbar*S*CL;       % 升力' newline ...
        'D = qbar*S*CD;       % 阻力' newline ...
        'Y = qbar*S*CYb*beta; % 侧力' newline ...
        '' newline ...
        '% 舵面力矩' newline ...
        'M_elev = qbar*S*c*Cmde*elev;' newline ...
        'L_ail  = qbar*S*b*Clda*ail;' newline ...
        'N_rud  = qbar*S*b*Cndr*rud;' newline ...
        '' newline ...
        '% 气动力矩' newline ...
        'Vc = V*c/(2);  % 无量纲化' newline ...
        'Vb = V*b/(2);' newline ...
        'M_pitch = qbar*S*c*(Cm0 + Cma*alpha + Cmq*q*Vc/V) + M_elev;' newline ...
        'M_roll  = qbar*S*b*(Clb*beta + Clp*p*Vb/V) + L_ail;' newline ...
        'M_yaw   = qbar*S*b*(Cnb*beta + Cnr*r*Vb/V) + N_rud;' newline ...
        '' newline ...
        '% 推力' newline ...
        'T = thr * 50;  % 最大推力 50N' newline ...
        '' newline ...
        '% 气动力转换到机体坐标' newline ...
        'ca=cos(alpha); sa=sin(alpha);' newline ...
        'Fx = -D*ca + L*sa + T;' newline ...
        'Fz = -D*sa - L*ca;' newline ...
        'Fy = Y;' newline ...
        '' newline ...
        '% 旋转矩阵 (ZYX)' newline ...
        'cp=cos(phi); sp=sin(phi);' newline ...
        'ct=cos(theta); st=sin(theta);' newline ...
        'cb=cos(psi); sb=sin(psi);' newline ...
        '' newline ...
        '% 重力在机体坐标' newline ...
        'gx = -g*st;' newline ...
        'gy =  g*ct*sp;' newline ...
        'gz =  g*ct*cp;' newline ...
        '' newline ...
        '% 加速度' newline ...
        'ax = Fx/m + gx;' newline ...
        'ay = Fy/m + gy;' newline ...
        'az = Fz/m + gz;' newline ...
        '' newline ...
        '% 欧拉方程 (含 Ixz 耦合)' newline ...
        'p_dot = (Izz*M_roll + Ixz*M_yaw - (Ixz*(Ixx-Iyy+Izz)*p*q ...' newline ...
        '         + (Iyy*Izz-Izz^2-Ixz^2)*q*r)) / (Ixx*Izz-Ixz^2);' newline ...
        'r_dot = (Ixx*M_yaw + Ixz*M_roll + (Ixz*(Ixx-Iyy+Izz)*q*r ...' newline ...
        '         + (Ixx^2-Ixx*Iyy+Ixz^2)*p*q)) / (Ixx*Izz-Ixz^2);' newline ...
        'q_dot = (M_pitch + (Izz-Ixx)*p*r + Ixz*(r^2-p^2)) / Iyy;' newline ...
        '' newline ...
        '% 欧拉角导数' newline ...
        'phi_dot   = p + q*sp*(st/ct) + r*cp*(st/ct);' newline ...
        'theta_dot = q*cp - r*sp;' newline ...
        'psi_dot   = q*sp/ct + r*cp/ct;' newline ...
        '' newline ...
        '% 世界坐标速度' newline ...
        'vx_w = ct*cb*vx + (sp*st*cb-cp*sb)*vy + (cp*st*cb+sp*sb)*vz;' newline ...
        'vy_w = ct*sb*vx + (sp*st*sb+cp*cb)*vy + (cp*st*sb-sp*cb)*vz;' newline ...
        'vz_w = -st*vx + sp*ct*vy + cp*ct*vz;' newline ...
        '' newline ...
        'state_dot = [vx_w;vy_w;vz_w; ax;ay;az;' newline ...
        '             phi_dot;theta_dot;psi_dot;' newline ...
        '             p_dot;q_dot;r_dot];' newline ...
        'end' newline
    ];

    try
        target.Script = code;
    catch
        try
            eml = target.find('-isa','Stateflow.EMFunction');
            if ~isempty(eml), eml(1).Script = code; end
        catch
            warning('自动设置代码失败, 请手动编辑 %s 中的 MATLAB Function', blk_path);
        end
    end
end

%% ==================== 工具函数 ====================
function add_mux(mdl, name, n, pos)
    add_block('simulink/Signal Routing/Mux', [mdl '/' name], ...
        'Position', pos, 'Inputs', num2str(n));
end
