function build_evtol_model()
%BUILD_EVTOL_MODEL  构建 eVTOL 倾转旋翼 Simulink 模型 (可直接运行)
%   生成 evtol_transition.slx
%   控制框图: 模式调度 → 悬停/巡航控制 → 混合 → 倾转6DOF → 反馈
%
%   用法:
%     cd E:\drone-simulink; init_project; build_evtol_model
%     open_system('evtol_transition')
%     sim('evtol_transition')

    mdl = 'evtol_transition';
    if bdIsLoaded(mdl), close_system(mdl, 0); end
    new_system(mdl); open_system(mdl);

    set_param(mdl, 'Solver','ode4','FixedStep','0.002','StopTime','120');
    set_param(mdl, 'SaveFormat','StructureWithTime');

    %% ========== 任务输入 ==========
    add_block('simulink/Sources/Constant', [mdl '/Alt_Des'], ...
        'Position',[30,80,70,100], 'Value','50');
    add_block('simulink/Sources/Step', [mdl '/V_Des'], ...
        'Position',[30,160,70,180], 'Time','15','After','25','Before','0');

    %% ========== 模式调度子系统 ==========
    add_block('simulink/Ports & Subsystems/Subsystem', [mdl '/Mode_Sched'], ...
        'Position',[170,55,350,190], 'BackgroundColor','cyan');
    build_mode_sched(mdl);

    %% ========== 悬停控制子系统 ==========
    add_block('simulink/Ports & Subsystems/Subsystem', [mdl '/Hover_Ctrl'], ...
        'Position',[420,30,600,110], 'BackgroundColor','green');
    build_hover_ctrl(mdl);

    %% ========== 巡航控制子系统 ==========
    add_block('simulink/Ports & Subsystems/Subsystem', [mdl '/Cruise_Ctrl'], ...
        'Position',[420,130,600,210], 'BackgroundColor','yellow');
    build_cruise_ctrl(mdl);

    %% ========== 混合器子系统 ==========
    add_block('simulink/Ports & Subsystems/Subsystem', [mdl '/Blend'], ...
        'Position',[660,55,820,200], 'BackgroundColor',[0.8,0.6,1]);
    build_blend(mdl);

    %% ========== eVTOL 动力学子系统 ==========
    add_block('simulink/Ports & Subsystems/Subsystem', [mdl '/eVTOL_Dyn'], ...
        'Position',[880,55,1100,200], 'BackgroundColor','red');
    build_evtol_dyn(mdl);

    %% ========== Demux ==========
    add_block('simulink/Signal Routing/Demux', [mdl '/Demux'], ...
        'Position',[1150,70,1155,195], 'Outputs','12');

    %% ========== 反馈 Mux ==========
    add_mux(mdl, 'Mux_Fb', 6, [110,280,115,390]);

    %% ========== Scope ==========
    add_block('simulink/Sinks/Scope', [mdl '/Scope_Pos'], ...
        'Position',[1250,40,1290,80]);
    add_block('simulink/Sinks/Scope', [mdl '/Scope_Tilt'], ...
        'Position',[1250,110,1290,150]);
    add_block('simulink/Sinks/To Workspace', [mdl '/ToWS'], ...
        'VariableName','evtol_state','Position',[1250,180,1290,210]);

    %% ========== 顶层连线 ==========
    add_line(mdl, 'Alt_Des/1', 'Mode_Sched/1');
    add_line(mdl, 'V_Des/1',   'Mode_Sched/2');

    add_line(mdl, 'Mode_Sched/1', 'Hover_Ctrl/1');
    add_line(mdl, 'Mode_Sched/2', 'Cruise_Ctrl/1');
    add_line(mdl, 'Alt_Des/1',    'Hover_Ctrl/2');
    add_line(mdl, 'Alt_Des/1',    'Cruise_Ctrl/2');
    add_line(mdl, 'V_Des/1',      'Cruise_Ctrl/3');

    add_line(mdl, 'Hover_Ctrl/1',  'Blend/1');
    add_line(mdl, 'Cruise_Ctrl/1', 'Blend/2');
    add_line(mdl, 'Mode_Sched/3',  'Blend/3');

    add_line(mdl, 'Blend/1', 'eVTOL_Dyn/1');
    add_line(mdl, 'Blend/2', 'eVTOL_Dyn/2');
    add_line(mdl, 'Blend/3', 'eVTOL_Dyn/3');

    add_line(mdl, 'eVTOL_Dyn/1', 'Demux/1');

    % 反馈
    add_line(mdl, 'Demux/1', 'Mux_Fb/1');
    add_line(mdl, 'Demux/2', 'Mux_Fb/2');
    add_line(mdl, 'Demux/3', 'Mux_Fb/3');
    add_line(mdl, 'Demux/7', 'Mux_Fb/4');
    add_line(mdl, 'Demux/8', 'Mux_Fb/5');
    add_line(mdl, 'Demux/9', 'Mux_Fb/6');
    add_line(mdl, 'Mux_Fb/1', 'Mode_Sched/3');

    add_line(mdl, 'Demux/3', 'Scope_Pos/1');
    add_line(mdl, 'Blend/3', 'Scope_Tilt/1');
    add_line(mdl, 'Demux/1', 'ToWS/1');

    %% 保存
    save_system(mdl, fullfile(pwd, [mdl '.slx']));
    fprintf('已生成: %s.slx — 打开后可直接运行\n', mdl);
end

%% ==================== 模式调度子系统 ====================
function build_mode_sched(mdl)
    sys = [mdl '/Mode_Sched'];
    delete_line(sys, 'In1/1', 'Out1/1');
    delete_block([sys '/In1']); delete_block([sys '/Out1']);

    add_block('simulink/Sources/In1', [sys '/alt_des'], 'Position',[20,40,40,55]);
    add_block('simulink/Sources/In1', [sys '/V_des'],   'Position',[20,100,40,115]);
    add_block('simulink/Sources/In1', [sys '/fb'],      'Position',[20,160,40,175]);
    add_block('simulink/Sinks/Out1',  [sys '/hover_mode'],'Position',[380,35,400,50]);
    add_block('simulink/Sinks/Out1',  [sys '/cruise_mode'],'Position',[380,90,400,105]);
    add_block('simulink/Sinks/Out1',  [sys '/alpha'],     'Position',[380,150,400,165]);

    % Demux 反馈: [x,y,z,phi,theta,psi]
    add_block('simulink/Signal Routing/Demux', [sys '/Dfb'], ...
        'Position',[70,145,75,215], 'Outputs','6');

    % alpha = clamp((V-5)/(20-5), 0, 1)  倾转比例
    add_block('simulink/Math Operations/Bias', [sys '/Vbias'], ...
        'Position',[140,95,170,115], 'Bias','-5');
    add_block('simulink/Math Operations/Gain', [sys '/Vscale'], ...
        'Position',[200,95,230,115], 'Gain','0.0667');
    add_block('simulink/Discontinuities/Saturation', [sys '/Vsat'], ...
        'Position',[260,95,300,115], 'UpperLimit','1','LowerLimit','0');

    % mode = alpha (same signal for hover/cruise blend)
    add_line(sys, 'V_des/1','Vbias/1');
    add_line(sys, 'Vbias/1','Vscale/1');
    add_line(sys, 'Vscale/1','Vsat/1');
    add_line(sys, 'Vsat/1','alpha/1');
    add_line(sys, 'Vsat/1','hover_mode/1');
    add_line(sys, 'Vsat/1','cruise_mode/1');
end

%% ==================== 悬停控制子系统 ====================
function build_hover_ctrl(mdl)
    sys = [mdl '/Hover_Ctrl'];
    delete_line(sys, 'In1/1', 'Out1/1');
    delete_block([sys '/In1']); delete_block([sys '/Out1']);

    add_block('simulink/Sources/In1', [sys '/alpha'],   'Position',[20,40,40,55]);
    add_block('simulink/Sources/In1', [sys '/alt_des'], 'Position',[20,100,40,115]);
    add_block('simulink/Sinks/Out1',  [sys '/omega_cmd'],'Position',[420,55,440,70]);

    % hover omega = sqrt(m*g/(4*kt)) = sqrt(12*9.81/(4*1.2e-5)) ~ 495
    add_block('simulink/Sources/Constant', [sys '/w0'], ...
        'Position',[80,55,130,75], 'Value','495');

    % 高度修正 PID
    add_block('simulink/Math Operations/Sum', [sys '/Se'], ...
        'Position',[180,40,200,60], 'Inputs','+-');
    add_block('simulink/Continuous/PID Controller', [sys '/PID_Z'], ...
        'Position',[240,35,340,65], 'P','2.0','I','0.3','D','1.0', ...
        'UpperSaturationLimit','200','LowerSaturationLimit','-200');
    add_block('simulink/Math Operations/Sum', [sys '/Sw'], ...
        'Position',[370,50,390,70], 'Inputs','++');

    add_line(sys, 'alt_des/1','Se/1');
    add_line(sys, 'Se/1','PID_Z/1');
    add_line(sys, 'w0/1','Sw/1');
    add_line(sys, 'PID_Z/1','Sw/2');
    add_line(sys, 'Sw/1','omega_cmd/1');
end

%% ==================== 巡航控制子系统 ====================
function build_cruise_ctrl(mdl)
    sys = [mdl '/Cruise_Ctrl'];
    delete_line(sys, 'In1/1', 'Out1/1');
    delete_block([sys '/In1']); delete_block([sys '/Out1']);

    add_block('simulink/Sources/In1', [sys '/alpha'],    'Position',[20,40,40,55]);
    add_block('simulink/Sources/In1', [sys '/alt_des'],  'Position',[20,100,40,115]);
    add_block('simulink/Sources/In1', [sys '/V_des'],    'Position',[20,160,40,175]);
    add_block('simulink/Sinks/Out1',  [sys '/push_cmd'], 'Position',[350,60,370,75]);

    % 推进器转速 = V_des * 40
    add_block('simulink/Math Operations/Gain', [sys '/V2w'], ...
        'Position',[150,155,200,175], 'Gain','40');
    add_block('simulink/Discontinuities/Saturation', [sys '/Sat'], ...
        'Position',[250,155,300,175], 'UpperLimit','2000','LowerLimit','0');

    add_line(sys, 'V_des/1','V2w/1');
    add_line(sys, 'V2w/1','Sat/1');
    add_line(sys, 'Sat/1','push_cmd/1');
end

%% ==================== 混合器子系统 ====================
function build_blend(mdl)
    sys = [mdl '/Blend'];
    delete_line(sys, 'In1/1', 'Out1/1');
    delete_block([sys '/In1']); delete_block([sys '/Out1']);

    add_block('simulink/Sources/In1', [sys '/hover_w'],  'Position',[20,30,40,45]);
    add_block('simulink/Sources/In1', [sys '/cruise_p'], 'Position',[20,90,40,105]);
    add_block('simulink/Sources/In1', [sys '/alpha'],    'Position',[20,150,40,165]);
    add_block('simulink/Sinks/Out1',  [sys '/lift_cmd'], 'Position',[420,30,440,45]);
    add_block('simulink/Sinks/Out1',  [sys '/push_cmd'], 'Position',[420,90,440,105]);
    add_block('simulink/Sinks/Out1',  [sys '/tilt_cmd'], 'Position',[420,150,440,165]);

    % lift = (1-alpha) * hover_w
    add_block('simulink/Math Operations/Sum', [sys '/Sa'], ...
        'Position',[100,145,120,165], 'Inputs','+-');
    add_block('simulink/Sources/Constant', [sys '/one'], ...
        'Position',[50,160,70,180], 'Value','1');
    add_block('simulink/Math Operations/Product', [sys '/Pl'], ...
        'Position',[200,30,220,50]);

    % push = alpha * cruise_p
    add_block('simulink/Math Operations/Product', [sys '/Pp'], ...
        'Position',[200,90,220,110]);

    % tilt = alpha * pi/2
    add_block('simulink/Math Operations/Gain', [sys '/toRad'], ...
        'Position',[250,145,290,165], 'Gain','1.5708');

    add_line(sys, 'one/1','Sa/1'); add_line(sys, 'alpha/1','Sa/2');
    add_line(sys, 'Sa/1','Pl/1'); add_line(sys, 'hover_w/1','Pl/2');
    add_line(sys, 'Pl/1','lift_cmd/1');
    add_line(sys, 'alpha/1','Pp/1'); add_line(sys, 'cruise_p/1','Pp/2');
    add_line(sys, 'Pp/1','push_cmd/1');
    add_line(sys, 'alpha/1','toRad/1');
    add_line(sys, 'toRad/1','tilt_cmd/1');
end

%% ==================== eVTOL 动力学子系统 ====================
function build_evtol_dyn(mdl)
    sys = [mdl '/eVTOL_Dyn'];
    delete_line(sys, 'In1/1', 'Out1/1');
    delete_block([sys '/In1']); delete_block([sys '/Out1']);

    add_block('simulink/Sources/In1', [sys '/lift_cmd'], 'Position',[20,40,40,55]);
    add_block('simulink/Sources/In1', [sys '/push_cmd'], 'Position',[20,100,40,115]);
    add_block('simulink/Sources/In1', [sys '/tilt_cmd'], 'Position',[20,160,40,175]);
    add_block('simulink/Sinks/Out1',  [sys '/state'],    'Position',[520,90,540,105]);

    add_block('simulink/User-Defined Functions/MATLAB Function', [sys '/ev6dof'], ...
        'Position',[130,50,370,170]);

    set_mafcn_code(sys, 'ev6dof');

    add_block('simulink/Continuous/Integrator', [sys '/Int'], ...
        'Position',[420,65,470,130], ...
        'InitialCondition','[0;0;-50;0;0;0;0;0;0;0;0;0]');

    add_line(sys, 'lift_cmd/1','ev6dof/1');
    add_line(sys, 'push_cmd/1','ev6dof/2');
    add_line(sys, 'tilt_cmd/1','ev6dof/3');
    add_line(sys, 'Int/1','ev6dof/4');
    add_line(sys, 'ev6dof/1','Int/1');
    add_line(sys, 'Int/1','state/1');
end

%% ==================== 设置 MATLAB Function 代码 ====================
function set_mafcn_code(sys, blk_name)
    blk_path = [sys '/' blk_name];
    rt = sfroot;
    all_blocks = rt.find('-isa','Stateflow.EMChart');
    target = [];
    for i = 1:numel(all_blocks)
        if contains(all_blocks(i).Path, blk_path)
            target = all_blocks(i);
            break;
        end
    end
    if isempty(target)
        try
            target = get_param(blk_path, 'SFChartObject');
        catch
            warning('无法设置 MATLAB Function 代码, 请手动编辑 %s', blk_path);
            return;
        end
    end

    code = [
        'function state_dot = ev6dof(lift_cmd, push_cmd, tilt_cmd, state)' newline ...
        '%#codegen' newline ...
        '%% eVTOL 倾转旋翼 6DOF 动力学' newline ...
        'm = 12; g = 9.81; rho = 1.225;' newline ...
        'kt = 1.2e-5; kd = 1.5e-7;' newline ...
        'Ixx = 0.8; Iyy = 1.5; Izz = 1.8;' newline ...
        'S = 0.8; b = 3.0; AR = b^2/S;' newline ...
        'CL0 = 0.2; CLa = 5.0; CD0 = 0.025; e_os = 0.75;' newline ...
        '' newline ...
        '% 状态解包' newline ...
        'x=state(1); y=state(2); z=state(3);' newline ...
        'vx=state(4); vy=state(5); vz=state(6);' newline ...
        'phi=state(7); theta=state(8); psi=state(9);' newline ...
        'p=state(10); q=state(11); r=state(12);' newline ...
        '' newline ...
        '% 倾转角 (限幅 0~90°)' newline ...
        'tilt = max(0, min(tilt_cmd, pi/2));' newline ...
        'ct_t = cos(tilt); st_t = sin(tilt);' newline ...
        '' newline ...
        '% 4 个升力旋翼 (倾转)' newline ...
        'w_lift = lift_cmd;  % 升力旋翼转速' newline ...
        'T_lift = 4*kt*w_lift^2;' newline ...
        '' newline ...
        '% 推进器' newline ...
        'w_push = push_cmd;' newline ...
        'T_push = kt*w_push^2 * 1.5;  % 推进器推力系数更大' newline ...
        '' newline ...
        '% 推力分量 (倾转分解)' newline ...
        'Tx = T_lift*st_t + T_push;' newline ...
        'Ty = 0;' newline ...
        'Tz = T_lift*ct_t;' newline ...
        '' newline ...
        '% 气动力 (巡航时有升力)' newline ...
        'V = sqrt(vx^2+vy^2+vz^2) + 1e-6;' newline ...
        'qbar = 0.5*rho*V^2;' newline ...
        '' newline ...
        '% 升力系数随倾转角混合' newline ...
        'alpha_fw = atan2(vz, vx);' newline ...
        'CL = CL0 + CLa*alpha_fw;' newline ...
        'CL = max(min(CL, 1.5), -1.0);' newline ...
        'CD = CD0 + CL^2/(pi*e_os*AR);' newline ...
        '' newline ...
        'L = qbar*S*CL * st_t;  % 巡航时气动升力' newline ...
        'D = qbar*S*CD;' newline ...
        '' newline ...
        '% 旋转矩阵' newline ...
        'cp=cos(phi); sp=sin(phi);' newline ...
        'ct=cos(theta); st=sin(theta);' newline ...
        'cb=cos(psi); sb=sin(psi);' newline ...
        '' newline ...
        '% 机体合力' newline ...
        'Fx = Tx - D*ct_t;' newline ...
        'Fy = Ty;' newline ...
        'Fz = Tz + L;' newline ...
        '' newline ...
        '% 加速度 (含重力)' newline ...
        'ax = Fx/m - g*st;' newline ...
        'ay = Fy/m + g*ct*sp;' newline ...
        'az = Fz/m + g*ct*cp;' newline ...
        '' newline ...
        '% 简化力矩 (悬停模式)' newline ...
        'arm = 1.2;  % 旋翼臂长' newline ...
        'tau_phi   = arm*kt*w_lift^2 * 0.5;' newline ...
        'tau_theta = arm*kt*w_lift^2 * 0.3;' newline ...
        'tau_psi   = kd*w_lift^2 * 2;' newline ...
        '' newline ...
        '% 角加速度' newline ...
        'p_dot = (tau_phi + (Iyy-Izz)*q*r) / Ixx;' newline ...
        'q_dot = (tau_theta + (Izz-Ixx)*p*r) / Iyy;' newline ...
        'r_dot = (tau_psi + (Ixx-Iyy)*p*q) / Izz;' newline ...
        '' newline ...
        '% 欧拉角导数' newline ...
        'phi_dot   = p + q*sp*(st/ct) + r*cp*(st/ct);' newline ...
        'theta_dot = q*cp - r*sp;' newline ...
        'psi_dot   = q*sp/ct + r*cp/ct;' newline ...
        '' newline ...
        '% 世界坐标速度' newline ...
        'vx_w = ct*cb*vx + (sp*st*cb-cp*sb)*vy + (cp*st*cb+sp*sb)*vz;' newline ...
        'vy_w = ct*sb*vx + (sp*st*sb+cp*cb)*vy + (cp*st*sb-sp*cb)*vz;' newline ...
        'vz_w = -st*vx + sp*ct*vy + cp*ct*vz;' newline ...
        '' newline ...
        'state_dot = [vx_w;vy_w;vz_w; ax;ay;az;' newline ...
        '             phi_dot;theta_dot;psi_dot;' newline ...
        '             p_dot;q_dot;r_dot];' newline ...
        'end' newline
    ];

    try
        target.Script = code;
    catch
        try
            eml = target.find('-isa','Stateflow.EMFunction');
            if ~isempty(eml), eml(1).Script = code; end
        catch
            warning('自动设置代码失败, 请手动编辑 %s 中的 MATLAB Function', blk_path);
        end
    end
end

%% ==================== 工具函数 ====================
function add_mux(mdl, name, n, pos)
    add_block('simulink/Signal Routing/Mux', [mdl '/' name], ...
        'Position', pos, 'Inputs', num2str(n));
end
